---
- hosts: all
  name: Postgres deployment playbook
  become: true
  gather_facts: true

  collections:
    - tmax_opensql.postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        pg_version: 14.6
        pg_type: "PG"
        disable_logging: false
    - name: Set variable
      ansible.builtin.include_vars:
        dir: vars
        ignore_unknown_extensions: True
        extensions:
          - 'yml'

  roles:
    - role: setup_repo
    - role: install_dbserver
    - role: init_dbserver
    - role: setup_replication
    - role: setup_pgpool2
    - role: manage_pgpool2
    - role: manage_dbserver
    - role: setup_pgbouncer
    - role: manage_pgbouncer
    - role: setup_barmanserver
    - role: setup_barman
    - role: autotuning
