name: send-dispatch-action

on:
  push:
    branches: [ master ]

jobs:
  trigger-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.ADMIN_USERNAME }}:${{ secrets.ADMIN_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/sungmu1/pg-ansible/dispatches \
               --data '{"event_type": "deploy-ansible-repository"}'
