name: custom-github-action

on:
  release:
    types: [published]

jobs:
  trigger-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "${{ secrets.ADMIN_USERNAME }}:${{ secrets.ADMIN_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/tmaxopensql/postgres-build-container/dispatches \
               --data '{"event_type": "deploy-ansible-repository"}'
